export enum ActionType {
  GET_FAVORITE_FRIENDS_SUCCESS = "GET_FAVORITE_FRIENDS_SUCCESS",
  GET_FAVORITE_FRIENDS_FAILURE = "GET_FAVORITE_FRIENDS_FAILURE",
  GET_FRIENDS_SUCCESS = "GET_FRIENDS_SUCCESS",
  GET_FRIENDS_FAILURE = "GET_FRIENDS_FAILURE",
  GET_GROUPS_SUCCESS = "GET_GROUPS_SUCCESS",
  GET_GROUPS_FAILURE = "GET_GROUPS_FAILURE",
  GET_USER_LOGIN_SUCCESS = "GET_USER_LOGIN_SUCCESS",
}
